#!/bin/bash
export DIRMAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )
source $DIRMAIN/config
mkdir -p ~/.cache/tpm
echo "Tina's Package Manager"
echo "----------------------"
echo ""

if [[ $1 == "-h" ]];
then
	echo "list of commands: -h, -d, -l"
	echo "-h: help"
	echo "-d: download"
	echo "-l: download"
elif [[ $1 == "-d" ]];
then
	if [[ $2 == "" ]];
	then
		echo "no file specified"
	else
		echo "Downloading $2 from $HOST:$PORT"
		curl $HOST:$PORT/$DIR/$2 -o ~/.cache/tpm/$2
		echo ""
		echo "Extracting Files..."
		mkdir -p $EDIR/$2
		tar -xvf  ~/.cache/tpm/$2 -C $EDIR/$2
		echo "cleaning up..."
		rm -rf ~/.cache/tpm
		echo "done"
	fi
elif [[ $1 == "-l" ]];
then
	curl $HOST:$PORT/$DIR/index.html
else
	echo "no command specified, use -h for a list of commands"
fi
